import Link from 'next/link'
import { ArrowRight, CheckCircle2, GitBranch, ListTodo, Plug, Sparkles } from 'lucide-react'

type DashboardData = {
  counts: { active: number; suggested: number; decisions: number; connectedIntegrations: number; needsAttention: number; savedContext: number; dueToday: number; overdue: number; sourcedAnswers: number }
  suggestedTasks: Array<{ id: string; title: string; sourceType: string | null; dueAt: string | null; priority: string }>
  priorityTasks: Array<{ id: string; title: string; sourceType: string | null; dueAt: string | null; priority: string; status: string }>
  recentDecisions: Array<{ id: string; title: string; source: string; date: string }>
  health: Array<{ name: string; status: string; lastSyncAt: string | null }>
}

const pretty = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase())
const dateLabel = (value: string | null) => value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : 'No date'

export default function DashboardOverview({ data }: { data: DashboardData }) {
  const cards = [
    { label: 'Active tasks', value: data.counts.active, note: 'Ready to work on', href: '/dashboard/tasks', icon: ListTodo },
    { label: 'Suggested tasks', value: data.counts.suggested, note: 'Waiting for review', href: '/dashboard/tasks', icon: Sparkles },
    { label: 'Decisions', value: data.counts.decisions, note: 'Remembered decisions', href: '/dashboard/decisions', icon: GitBranch },
    { label: 'Integrations', value: data.counts.connectedIntegrations, note: 'Connected tools', href: '/dashboard/integrations', icon: Plug },
  ]
  const empty = data.counts.savedContext === 0 && data.counts.active === 0 && data.counts.suggested === 0 && data.counts.decisions === 0 && data.counts.connectedIntegrations === 0

  return <div className="mx-auto max-w-7xl space-y-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight text-gray-950">Dashboard</h1><p className="mt-1 text-sm text-gray-500">Your workspace at a glance.</p></div><p className="text-xs text-gray-400">Updated {new Date().toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</p></header>
    {empty && <section className="rounded-2xl border border-indigo-100 bg-indigo-50/60 p-6"><h2 className="font-semibold text-gray-900">Set up your workspace</h2><p className="mt-1 text-sm text-gray-600">Connect an integration or query Neuron to get started.</p><div className="mt-4 flex gap-3"><Link href="/dashboard/integrations" className="rounded-lg bg-gray-900 px-4 py-2 text-sm font-medium text-white">Connect integration</Link><Link href="/dashboard/query" className="rounded-lg border bg-white px-4 py-2 text-sm font-medium">Open Query</Link></div></section>}
    <section aria-label="Dashboard overview" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ label, value, note, href, icon: Icon }) => <Link key={label} href={href} className="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className="rounded-xl bg-gray-50 p-2 text-gray-600"><Icon className="h-5 w-5"/></span><ArrowRight className="h-4 w-4 text-gray-300 transition group-hover:translate-x-0.5"/></div><p className="mt-4 text-3xl font-semibold text-gray-950">{value}</p><p className="mt-1 text-sm font-medium text-gray-800">{label}</p><p className="text-xs text-gray-500">{note}</p></Link>)}</section>
    <section className="rounded-2xl border border-indigo-100 bg-indigo-50/50 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold text-gray-900">{data.counts.sourcedAnswers >= 3 ? 'Your company brain is ready.' : 'Finish setting up your company brain'}</h2><p className="mt-1 text-sm text-gray-600">Connect context, ask 3 real questions, and get sourced answers.</p></div><div className="text-right"><p className="text-2xl font-semibold text-indigo-700">{Math.min(data.counts.sourcedAnswers, 3)}/3</p><p className="text-xs text-indigo-600">sourced answers</p></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-indigo-600 transition-all" style={{ width: `${Math.min(data.counts.sourcedAnswers / 3, 1) * 100}%` }}/></div></section>
    <section className="grid items-start gap-6 lg:grid-cols-[1.2fr_.8fr]"><Panel title="Today" link="/dashboard/tasks" linkLabel="View all tasks"><div className="grid grid-cols-3 gap-2"><Mini label="Due today" value={data.counts.dueToday}/><Mini label="Overdue" value={data.counts.overdue} warning={data.counts.overdue > 0}/><Mini label="Suggested" value={data.counts.suggested}/></div><div className="mt-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-gray-400">Priority today</p>{data.priorityTasks.length > 0 ? <div className="space-y-2">{data.priorityTasks.map(task => <Link href="/dashboard/tasks" key={task.id} className="flex items-center gap-3 rounded-xl border border-gray-100 px-3 py-2.5 transition hover:border-indigo-200"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-gray-900">{task.title}</p><p className="mt-0.5 text-xs text-gray-400">{dateLabel(task.dueAt)}</p></div><span className="rounded-full bg-blue-50 px-2 py-0.5 text-[11px] text-blue-700">{pretty(task.sourceType ?? 'manual')}</span><span className={task.priority === 'urgent' || task.priority === 'high' ? 'rounded-full bg-orange-50 px-2 py-0.5 text-[11px] text-orange-700' : 'rounded-full bg-gray-100 px-2 py-0.5 text-[11px] text-gray-600'}>{pretty(task.priority)}</span><span className="text-[11px] capitalize text-gray-400">{task.status}</span></Link>)}</div> : <p className="rounded-xl bg-gray-50 px-3 py-3 text-sm text-gray-500">No urgent tasks today. You’re clear for now.</p>}</div></Panel><Panel title="Integration health" link="/dashboard/integrations" linkLabel="View integrations"><div className="space-y-2">{data.health.slice(0, 5).map(item => <div key={`${item.name}-${item.status}`} className="flex items-center justify-between rounded-lg bg-gray-50 px-3 py-2 text-sm"><span className="font-medium">{pretty(item.name)}</span><span className={item.status === 'Healthy' ? 'text-emerald-600' : item.status === 'Upcoming' ? 'text-gray-400' : 'text-amber-600'}>{item.status}</span></div>)}{data.health.length === 0 && <p className="text-sm text-gray-500">No integrations connected yet.</p>}</div></Panel></section>
    <section className="grid gap-6 lg:grid-cols-2"><Panel title="Suggested tasks" link="/dashboard/tasks" linkLabel="View all tasks"><div className="space-y-3">{data.suggestedTasks.map(task => <div key={task.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><p className="text-sm font-medium text-gray-900">{task.title}</p><span className="text-xs text-gray-400">{dateLabel(task.dueAt)}</span></div><div className="mt-2 flex gap-2 text-[11px]"><span className="rounded-full bg-blue-50 px-2 py-0.5 text-blue-700">{pretty(task.sourceType ?? 'manual')}</span><span className="rounded-full bg-gray-100 px-2 py-0.5">{pretty(task.priority)}</span><Link href="/dashboard/tasks" className="ml-auto font-medium text-indigo-600">Review</Link></div></div>)}{data.suggestedTasks.length === 0 && <p className="text-sm text-gray-500">No suggested tasks right now.</p>}</div></Panel><Panel title="Recent decisions" link="/dashboard/decisions" linkLabel="View all decisions"><div className="space-y-3">{data.recentDecisions.map(decision => <div key={decision.id} className="flex items-start gap-3 rounded-xl border p-3"><CheckCircle2 className="mt-0.5 h-4 w-4 text-emerald-500"/><div><p className="text-sm font-medium">{decision.title}</p><p className="text-xs text-gray-400">{pretty(decision.source)} · {dateLabel(decision.date)}</p></div></div>)}{data.recentDecisions.length === 0 && <p className="text-sm text-gray-500">No decisions yet.</p>}</div></Panel></section>
  </div>
}

function Panel({ title, children, link, linkLabel }: { title: string; children: React.ReactNode; link?: string; linkLabel?: string }) { return <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold text-gray-900">{title}</h2>{link && <Link href={link} className="text-xs font-medium text-indigo-600">{linkLabel}</Link>}</div>{children}</section> }
function Mini({ label, value, warning }: { label: string; value: number; warning?: boolean }) { return <div className={warning ? 'rounded-xl bg-red-50 p-4' : 'rounded-xl bg-gray-50 p-4'}><p className={warning ? 'text-2xl font-semibold text-red-700' : 'text-2xl font-semibold text-gray-900'}>{value}</p><p className="text-xs text-gray-500">{label}</p></div> }
